/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalendarEvent {
  'id' : bigint,
  'startTime' : bigint,
  'status' : EventStatus,
  'title' : string,
  'clientId' : bigint,
  'endTime' : bigint,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'colorTag' : string,
  'assignedTeamMemberIds' : Array<bigint>,
  'notes' : string,
  'requirements' : Array<string>,
  'budget' : [] | [number],
  'location' : string,
  'eventType' : EventType,
}
export interface CalendarTask {
  'id' : bigint,
  'eventId' : bigint,
  'title' : string,
  'assignedTo' : [] | [string],
  'isCompleted' : boolean,
  'createdAt' : bigint,
  'dueDate' : [] | [bigint],
  'description' : string,
}
export interface Client {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'company' : string,
  'notes' : string,
  'phone' : string,
}
export type EventStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'planned' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export type EventType = { 'other' : null } |
  { 'conference' : null } |
  { 'wedding' : null } |
  { 'birthday' : null } |
  { 'corporate' : null };
export interface Reminder {
  'id' : bigint,
  'eventId' : bigint,
  'offsetMinutes' : bigint,
  'reminderLabel' : string,
  'isTriggered' : boolean,
}
export interface TeamMember {
  'id' : bigint,
  'name' : string,
  'role' : TeamMemberRole,
  'isActive' : boolean,
  'email' : string,
}
export type TeamMemberRole = { 'member' : null } |
  { 'manager' : null } |
  { 'admin' : null };
export interface UserProfile {
  'name' : string,
  'role' : TeamMemberRole,
  'isActive' : boolean,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTeamMemberToEvent' : ActorMethod<[bigint, bigint], undefined>,
  'createClient' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'createEvent' : ActorMethod<
    [
      bigint,
      string,
      EventType,
      EventStatus,
      bigint,
      bigint,
      string,
      Array<string>,
      [] | [number],
      string,
      Array<bigint>,
      string,
    ],
    bigint
  >,
  'createReminder' : ActorMethod<[bigint, bigint, string], bigint>,
  'createTask' : ActorMethod<
    [bigint, string, string, [] | [string], [] | [bigint]],
    bigint
  >,
  'createTeamMember' : ActorMethod<[string, string, TeamMemberRole], bigint>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteReminder' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'deleteTeamMember' : ActorMethod<[bigint], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[bigint], [] | [Client]>,
  'getDashboardData' : ActorMethod<
    [],
    {
      'overdueTasks' : Array<CalendarTask>,
      'todaysEvents' : Array<CalendarEvent>,
      'upcomingEvents' : Array<CalendarEvent>,
      'eventCountsByStatus' : Array<[EventStatus, bigint]>,
    }
  >,
  'getEvent' : ActorMethod<[bigint], [] | [CalendarEvent]>,
  'getEventsByClient' : ActorMethod<[bigint], Array<CalendarEvent>>,
  'getEventsByDateRange' : ActorMethod<[bigint, bigint], Array<CalendarEvent>>,
  'getEventsByStatus' : ActorMethod<[EventStatus], Array<CalendarEvent>>,
  'getEventsByType' : ActorMethod<[EventType], Array<CalendarEvent>>,
  'getOverdueTasks' : ActorMethod<[], Array<CalendarTask>>,
  'getReminder' : ActorMethod<[bigint], [] | [Reminder]>,
  'getRemindersByEvent' : ActorMethod<[bigint], Array<Reminder>>,
  'getRemindersDueSoon' : ActorMethod<[], Array<Reminder>>,
  'getTask' : ActorMethod<[bigint], [] | [CalendarTask]>,
  'getTasksByEvent' : ActorMethod<[bigint], Array<CalendarTask>>,
  'getTeamMember' : ActorMethod<[bigint], [] | [TeamMember]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchEvents' : ActorMethod<[string], Array<CalendarEvent>>,
  'toggleTaskCompletion' : ActorMethod<[bigint], undefined>,
  'unassignTeamMemberFromEvent' : ActorMethod<[bigint, bigint], undefined>,
  'updateClient' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateEvent' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      EventType,
      EventStatus,
      bigint,
      bigint,
      string,
      Array<string>,
      [] | [number],
      string,
      Array<bigint>,
      string,
    ],
    undefined
  >,
  'updateReminder' : ActorMethod<[bigint, bigint, string, boolean], undefined>,
  'updateTask' : ActorMethod<
    [bigint, string, string, [] | [string], [] | [bigint], boolean],
    undefined
  >,
  'updateTeamMember' : ActorMethod<
    [bigint, string, string, TeamMemberRole, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];