/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventType = IDL.Variant({
  'other' : IDL.Null,
  'conference' : IDL.Null,
  'wedding' : IDL.Null,
  'birthday' : IDL.Null,
  'corporate' : IDL.Null,
});
export const EventStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TeamMemberRole = IDL.Variant({
  'member' : IDL.Null,
  'manager' : IDL.Null,
  'admin' : IDL.Null,
});
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const CalendarEvent = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : EventStatus,
  'title' : IDL.Text,
  'clientId' : IDL.Nat,
  'endTime' : IDL.Int,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'colorTag' : IDL.Text,
  'assignedTeamMemberIds' : IDL.Vec(IDL.Nat),
  'notes' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'budget' : IDL.Opt(IDL.Float64),
  'location' : IDL.Text,
  'eventType' : EventType,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : TeamMemberRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : TeamMemberRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const CalendarTask = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Text),
  'isCompleted' : IDL.Bool,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'offsetMinutes' : IDL.Nat,
  'reminderLabel' : IDL.Text,
  'isTriggered' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTeamMemberToEvent' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createEvent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        EventType,
        EventStatus,
        IDL.Int,
        IDL.Int,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createReminder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
      [IDL.Nat],
      [],
    ),
  'createTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, TeamMemberRole],
      [IDL.Nat],
      [],
    ),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteReminder' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Nat], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
  'getDashboardData' : IDL.Func(
      [],
      [
        IDL.Record({
          'overdueTasks' : IDL.Vec(CalendarTask),
          'todaysEvents' : IDL.Vec(CalendarEvent),
          'upcomingEvents' : IDL.Vec(CalendarEvent),
          'eventCountsByStatus' : IDL.Vec(IDL.Tuple(EventStatus, IDL.Nat)),
        }),
      ],
      ['query'],
    ),
  'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(CalendarEvent)], ['query']),
  'getEventsByClient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CalendarEvent)],
      ['query'],
    ),
  'getEventsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(CalendarEvent)],
      ['query'],
    ),
  'getEventsByStatus' : IDL.Func(
      [EventStatus],
      [IDL.Vec(CalendarEvent)],
      ['query'],
    ),
  'getEventsByType' : IDL.Func(
      [EventType],
      [IDL.Vec(CalendarEvent)],
      ['query'],
    ),
  'getOverdueTasks' : IDL.Func([], [IDL.Vec(CalendarTask)], ['query']),
  'getReminder' : IDL.Func([IDL.Nat], [IDL.Opt(Reminder)], ['query']),
  'getRemindersByEvent' : IDL.Func([IDL.Nat], [IDL.Vec(Reminder)], ['query']),
  'getRemindersDueSoon' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(CalendarTask)], ['query']),
  'getTasksByEvent' : IDL.Func([IDL.Nat], [IDL.Vec(CalendarTask)], ['query']),
  'getTeamMember' : IDL.Func([IDL.Nat], [IDL.Opt(TeamMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchEvents' : IDL.Func([IDL.Text], [IDL.Vec(CalendarEvent)], ['query']),
  'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
  'unassignTeamMemberFromEvent' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateClient' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateEvent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        EventType,
        EventStatus,
        IDL.Int,
        IDL.Int,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateReminder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'updateTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateTeamMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, TeamMemberRole, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventType = IDL.Variant({
    'other' : IDL.Null,
    'conference' : IDL.Null,
    'wedding' : IDL.Null,
    'birthday' : IDL.Null,
    'corporate' : IDL.Null,
  });
  const EventStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TeamMemberRole = IDL.Variant({
    'member' : IDL.Null,
    'manager' : IDL.Null,
    'admin' : IDL.Null,
  });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CalendarEvent = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : EventStatus,
    'title' : IDL.Text,
    'clientId' : IDL.Nat,
    'endTime' : IDL.Int,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'colorTag' : IDL.Text,
    'assignedTeamMemberIds' : IDL.Vec(IDL.Nat),
    'notes' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'budget' : IDL.Opt(IDL.Float64),
    'location' : IDL.Text,
    'eventType' : EventType,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : TeamMemberRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : TeamMemberRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const CalendarTask = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Text),
    'isCompleted' : IDL.Bool,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'offsetMinutes' : IDL.Nat,
    'reminderLabel' : IDL.Text,
    'isTriggered' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTeamMemberToEvent' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createEvent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          EventType,
          EventStatus,
          IDL.Int,
          IDL.Int,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createReminder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Int)],
        [IDL.Nat],
        [],
      ),
    'createTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, TeamMemberRole],
        [IDL.Nat],
        [],
      ),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteReminder' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Nat], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
    'getDashboardData' : IDL.Func(
        [],
        [
          IDL.Record({
            'overdueTasks' : IDL.Vec(CalendarTask),
            'todaysEvents' : IDL.Vec(CalendarEvent),
            'upcomingEvents' : IDL.Vec(CalendarEvent),
            'eventCountsByStatus' : IDL.Vec(IDL.Tuple(EventStatus, IDL.Nat)),
          }),
        ],
        ['query'],
      ),
    'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(CalendarEvent)], ['query']),
    'getEventsByClient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CalendarEvent)],
        ['query'],
      ),
    'getEventsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(CalendarEvent)],
        ['query'],
      ),
    'getEventsByStatus' : IDL.Func(
        [EventStatus],
        [IDL.Vec(CalendarEvent)],
        ['query'],
      ),
    'getEventsByType' : IDL.Func(
        [EventType],
        [IDL.Vec(CalendarEvent)],
        ['query'],
      ),
    'getOverdueTasks' : IDL.Func([], [IDL.Vec(CalendarTask)], ['query']),
    'getReminder' : IDL.Func([IDL.Nat], [IDL.Opt(Reminder)], ['query']),
    'getRemindersByEvent' : IDL.Func([IDL.Nat], [IDL.Vec(Reminder)], ['query']),
    'getRemindersDueSoon' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(CalendarTask)], ['query']),
    'getTasksByEvent' : IDL.Func([IDL.Nat], [IDL.Vec(CalendarTask)], ['query']),
    'getTeamMember' : IDL.Func([IDL.Nat], [IDL.Opt(TeamMember)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchEvents' : IDL.Func([IDL.Text], [IDL.Vec(CalendarEvent)], ['query']),
    'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
    'unassignTeamMemberFromEvent' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateClient' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateEvent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          EventType,
          EventStatus,
          IDL.Int,
          IDL.Int,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateReminder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'updateTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateTeamMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, TeamMemberRole, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };