/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CalendarEvent {
    id: bigint;
    startTime: bigint;
    status: EventStatus;
    title: string;
    clientId: bigint;
    endTime: bigint;
    createdAt: bigint;
    updatedAt: bigint;
    colorTag: string;
    assignedTeamMemberIds: Array<bigint>;
    notes: string;
    requirements: Array<string>;
    budget?: number;
    location: string;
    eventType: EventType;
}
export interface Reminder {
    id: bigint;
    eventId: bigint;
    offsetMinutes: bigint;
    reminderLabel: string;
    isTriggered: boolean;
}
export interface TeamMember {
    id: bigint;
    name: string;
    role: TeamMemberRole;
    isActive: boolean;
    email: string;
}
export interface Client {
    id: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    company: string;
    notes: string;
    phone: string;
}
export interface CalendarTask {
    id: bigint;
    eventId: bigint;
    title: string;
    assignedTo?: string;
    isCompleted: boolean;
    createdAt: bigint;
    dueDate?: bigint;
    description: string;
}
export interface UserProfile {
    name: string;
    role: TeamMemberRole;
    isActive: boolean;
    email: string;
}
export enum EventStatus {
    cancelled = "cancelled",
    completed = "completed",
    planned = "planned",
    confirmed = "confirmed",
    inProgress = "inProgress"
}
export enum EventType {
    other = "other",
    conference = "conference",
    wedding = "wedding",
    birthday = "birthday",
    corporate = "corporate"
}
export enum TeamMemberRole {
    member = "member",
    manager = "manager",
    admin = "admin"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignTeamMemberToEvent(eventId: bigint, teamMemberId: bigint): Promise<void>;
    createClient(name: string, email: string, phone: string, company: string, notes: string): Promise<bigint>;
    createEvent(clientId: bigint, title: string, eventType: EventType, status: EventStatus, startTime: bigint, endTime: bigint, location: string, requirements: Array<string>, budget: number | null, notes: string, assignedTeamMemberIds: Array<bigint>, colorTag: string): Promise<bigint>;
    createReminder(eventId: bigint, offsetMinutes: bigint, reminderLabel: string): Promise<bigint>;
    createTask(eventId: bigint, title: string, description: string, assignedTo: string | null, dueDate: bigint | null): Promise<bigint>;
    createTeamMember(name: string, email: string, role: TeamMemberRole): Promise<bigint>;
    deleteClient(id: bigint): Promise<void>;
    deleteEvent(id: bigint): Promise<void>;
    deleteReminder(id: bigint): Promise<void>;
    deleteTask(id: bigint): Promise<void>;
    deleteTeamMember(id: bigint): Promise<void>;
    getAllClients(): Promise<Array<Client>>;
    getAllEvents(): Promise<Array<CalendarEvent>>;
    getAllTeamMembers(): Promise<Array<TeamMember>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(id: bigint): Promise<Client | null>;
    getDashboardData(): Promise<{
        overdueTasks: Array<CalendarTask>;
        todaysEvents: Array<CalendarEvent>;
        upcomingEvents: Array<CalendarEvent>;
        eventCountsByStatus: Array<[EventStatus, bigint]>;
    }>;
    getEvent(id: bigint): Promise<CalendarEvent | null>;
    getEventsByClient(clientId: bigint): Promise<Array<CalendarEvent>>;
    getEventsByDateRange(startTime: bigint, endTime: bigint): Promise<Array<CalendarEvent>>;
    getEventsByStatus(status: EventStatus): Promise<Array<CalendarEvent>>;
    getEventsByType(eventType: EventType): Promise<Array<CalendarEvent>>;
    getOverdueTasks(): Promise<Array<CalendarTask>>;
    getReminder(id: bigint): Promise<Reminder | null>;
    getRemindersByEvent(eventId: bigint): Promise<Array<Reminder>>;
    getRemindersDueSoon(): Promise<Array<Reminder>>;
    getTask(id: bigint): Promise<CalendarTask | null>;
    getTasksByEvent(eventId: bigint): Promise<Array<CalendarTask>>;
    getTeamMember(id: bigint): Promise<TeamMember | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchEvents(keyword: string): Promise<Array<CalendarEvent>>;
    toggleTaskCompletion(id: bigint): Promise<void>;
    unassignTeamMemberFromEvent(eventId: bigint, teamMemberId: bigint): Promise<void>;
    updateClient(id: bigint, name: string, email: string, phone: string, company: string, notes: string): Promise<void>;
    updateEvent(id: bigint, clientId: bigint, title: string, eventType: EventType, status: EventStatus, startTime: bigint, endTime: bigint, location: string, requirements: Array<string>, budget: number | null, notes: string, assignedTeamMemberIds: Array<bigint>, colorTag: string): Promise<void>;
    updateReminder(id: bigint, offsetMinutes: bigint, reminderLabel: string, isTriggered: boolean): Promise<void>;
    updateTask(id: bigint, title: string, description: string, assignedTo: string | null, dueDate: bigint | null, isCompleted: boolean): Promise<void>;
    updateTeamMember(id: bigint, name: string, email: string, role: TeamMemberRole, isActive: boolean): Promise<void>;
}
import type { CalendarEvent as _CalendarEvent, CalendarTask as _CalendarTask, Client as _Client, EventStatus as _EventStatus, EventType as _EventType, Reminder as _Reminder, TeamMember as _TeamMember, TeamMemberRole as _TeamMemberRole, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignTeamMemberToEvent(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTeamMemberToEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTeamMemberToEvent(arg0, arg1);
            return result;
        }
    }
    async createClient(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createEvent(arg0: bigint, arg1: string, arg2: EventType, arg3: EventStatus, arg4: bigint, arg5: bigint, arg6: string, arg7: Array<string>, arg8: number | null, arg9: string, arg10: Array<bigint>, arg11: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, to_candid_EventType_n3(this._uploadFile, this._downloadFile, arg2), to_candid_EventStatus_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, to_candid_EventType_n3(this._uploadFile, this._downloadFile, arg2), to_candid_EventStatus_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11);
            return result;
        }
    }
    async createReminder(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReminder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReminder(arg0, arg1, arg2);
            return result;
        }
    }
    async createTask(arg0: bigint, arg1: string, arg2: string, arg3: string | null, arg4: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createTeamMember(arg0: string, arg1: string, arg2: TeamMemberRole): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeamMember(arg0, arg1, to_candid_TeamMemberRole_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeamMember(arg0, arg1, to_candid_TeamMemberRole_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteClient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteReminder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteTeamMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeamMember(arg0);
            return result;
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllEvents(): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamMembers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamMembers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: bigint): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardData(): Promise<{
        overdueTasks: Array<CalendarTask>;
        todaysEvents: Array<CalendarEvent>;
        upcomingEvents: Array<CalendarEvent>;
        eventCountsByStatus: Array<[EventStatus, bigint]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardData();
                return from_candid_record_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardData();
            return from_candid_record_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: bigint): Promise<CalendarEvent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByClient(arg0: bigint): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByClient(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByClient(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByDateRange(arg0: bigint, arg1: bigint): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByDateRange(arg0, arg1);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByDateRange(arg0, arg1);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByStatus(arg0: EventStatus): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByStatus(to_candid_EventStatus_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByStatus(to_candid_EventStatus_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByType(arg0: EventType): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByType(to_candid_EventType_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByType(to_candid_EventType_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverdueTasks(): Promise<Array<CalendarTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueTasks();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueTasks();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminder(arg0: bigint): Promise<Reminder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminder(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminder(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRemindersByEvent(arg0: bigint): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemindersByEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemindersByEvent(arg0);
            return result;
        }
    }
    async getRemindersDueSoon(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemindersDueSoon();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemindersDueSoon();
            return result;
        }
    }
    async getTask(arg0: bigint): Promise<CalendarTask | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByEvent(arg0: bigint): Promise<Array<CalendarTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByEvent(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByEvent(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamMember(arg0: bigint): Promise<TeamMember | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMember(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMember(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchEvents(arg0: string): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEvents(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEvents(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleTaskCompletion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskCompletion(arg0);
            return result;
        }
    }
    async unassignTeamMemberFromEvent(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unassignTeamMemberFromEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unassignTeamMemberFromEvent(arg0, arg1);
            return result;
        }
    }
    async updateClient(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: bigint, arg2: string, arg3: EventType, arg4: EventStatus, arg5: bigint, arg6: bigint, arg7: string, arg8: Array<string>, arg9: number | null, arg10: string, arg11: Array<bigint>, arg12: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1, arg2, to_candid_EventType_n3(this._uploadFile, this._downloadFile, arg3), to_candid_EventStatus_n5(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1, arg2, to_candid_EventType_n3(this._uploadFile, this._downloadFile, arg3), to_candid_EventStatus_n5(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
            return result;
        }
    }
    async updateReminder(arg0: bigint, arg1: bigint, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string, arg3: string | null, arg4: bigint | null, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateTeamMember(arg0: bigint, arg1: string, arg2: string, arg3: TeamMemberRole, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamMember(arg0, arg1, arg2, to_candid_TeamMemberRole_n10(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamMember(arg0, arg1, arg2, to_candid_TeamMemberRole_n10(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_CalendarEvent_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalendarEvent): CalendarEvent {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_CalendarTask_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalendarTask): CalendarTask {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_EventStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventStatus): EventStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TeamMemberRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMemberRole): TeamMemberRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TeamMember_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMember): TeamMember {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CalendarEvent]): CalendarEvent | null {
    return value.length === 0 ? null : from_candid_CalendarEvent_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Reminder]): Reminder | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CalendarTask]): CalendarTask | null {
    return value.length === 0 ? null : from_candid_CalendarTask_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamMember]): TeamMember | null {
    return value.length === 0 ? null : from_candid_TeamMember_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    status: _EventStatus;
    title: string;
    clientId: bigint;
    endTime: bigint;
    createdAt: bigint;
    updatedAt: bigint;
    colorTag: string;
    assignedTeamMemberIds: Array<bigint>;
    notes: string;
    requirements: Array<string>;
    budget: [] | [number];
    location: string;
    eventType: _EventType;
}): {
    id: bigint;
    startTime: bigint;
    status: EventStatus;
    title: string;
    clientId: bigint;
    endTime: bigint;
    createdAt: bigint;
    updatedAt: bigint;
    colorTag: string;
    assignedTeamMemberIds: Array<bigint>;
    notes: string;
    requirements: Array<string>;
    budget?: number;
    location: string;
    eventType: EventType;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_EventStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        clientId: value.clientId,
        endTime: value.endTime,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        colorTag: value.colorTag,
        assignedTeamMemberIds: value.assignedTeamMemberIds,
        notes: value.notes,
        requirements: value.requirements,
        budget: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.budget)),
        location: value.location,
        eventType: from_candid_EventType_n18(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: _TeamMemberRole;
    isActive: boolean;
    email: string;
}): {
    id: bigint;
    name: string;
    role: TeamMemberRole;
    isActive: boolean;
    email: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_TeamMemberRole_n23(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _TeamMemberRole;
    isActive: boolean;
    email: string;
}): {
    name: string;
    role: TeamMemberRole;
    isActive: boolean;
    email: string;
} {
    return {
        name: value.name,
        role: from_candid_TeamMemberRole_n23(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    overdueTasks: Array<_CalendarTask>;
    todaysEvents: Array<_CalendarEvent>;
    upcomingEvents: Array<_CalendarEvent>;
    eventCountsByStatus: Array<[_EventStatus, bigint]>;
}): {
    overdueTasks: Array<CalendarTask>;
    todaysEvents: Array<CalendarEvent>;
    upcomingEvents: Array<CalendarEvent>;
    eventCountsByStatus: Array<[EventStatus, bigint]>;
} {
    return {
        overdueTasks: from_candid_vec_n32(_uploadFile, _downloadFile, value.overdueTasks),
        todaysEvents: from_candid_vec_n12(_uploadFile, _downloadFile, value.todaysEvents),
        upcomingEvents: from_candid_vec_n12(_uploadFile, _downloadFile, value.upcomingEvents),
        eventCountsByStatus: from_candid_vec_n37(_uploadFile, _downloadFile, value.eventCountsByStatus)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    eventId: bigint;
    title: string;
    assignedTo: [] | [string];
    isCompleted: boolean;
    createdAt: bigint;
    dueDate: [] | [bigint];
    description: string;
}): {
    id: bigint;
    eventId: bigint;
    title: string;
    assignedTo?: string;
    isCompleted: boolean;
    createdAt: bigint;
    dueDate?: bigint;
    description: string;
} {
    return {
        id: value.id,
        eventId: value.eventId,
        title: value.title,
        assignedTo: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.assignedTo)),
        isCompleted: value.isCompleted,
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description
    };
}
function from_candid_tuple_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_EventStatus, bigint]): [EventStatus, bigint] {
    return [
        from_candid_EventStatus_n15(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    completed: null;
} | {
    planned: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
}): EventStatus {
    return "cancelled" in value ? EventStatus.cancelled : "completed" in value ? EventStatus.completed : "planned" in value ? EventStatus.planned : "confirmed" in value ? EventStatus.confirmed : "inProgress" in value ? EventStatus.inProgress : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    conference: null;
} | {
    wedding: null;
} | {
    birthday: null;
} | {
    corporate: null;
}): EventType {
    return "other" in value ? EventType.other : "conference" in value ? EventType.conference : "wedding" in value ? EventType.wedding : "birthday" in value ? EventType.birthday : "corporate" in value ? EventType.corporate : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    manager: null;
} | {
    admin: null;
}): TeamMemberRole {
    return "member" in value ? TeamMemberRole.member : "manager" in value ? TeamMemberRole.manager : "admin" in value ? TeamMemberRole.admin : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CalendarEvent>): Array<CalendarEvent> {
    return value.map((x)=>from_candid_CalendarEvent_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamMember>): Array<TeamMember> {
    return value.map((x)=>from_candid_TeamMember_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CalendarTask>): Array<CalendarTask> {
    return value.map((x)=>from_candid_CalendarTask_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_EventStatus, bigint]>): Array<[EventStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n38(_uploadFile, _downloadFile, x));
}
function to_candid_EventStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): _EventStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_EventType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TeamMemberRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamMemberRole): _TeamMemberRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: TeamMemberRole;
    isActive: boolean;
    email: string;
}): {
    name: string;
    role: _TeamMemberRole;
    isActive: boolean;
    email: string;
} {
    return {
        name: value.name,
        role: to_candid_TeamMemberRole_n10(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamMemberRole): {
    member: null;
} | {
    manager: null;
} | {
    admin: null;
} {
    return value == TeamMemberRole.member ? {
        member: null
    } : value == TeamMemberRole.manager ? {
        manager: null
    } : value == TeamMemberRole.admin ? {
        admin: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    other: null;
} | {
    conference: null;
} | {
    wedding: null;
} | {
    birthday: null;
} | {
    corporate: null;
} {
    return value == EventType.other ? {
        other: null
    } : value == EventType.conference ? {
        conference: null
    } : value == EventType.wedding ? {
        wedding: null
    } : value == EventType.birthday ? {
        birthday: null
    } : value == EventType.corporate ? {
        corporate: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): {
    cancelled: null;
} | {
    completed: null;
} | {
    planned: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
} {
    return value == EventStatus.cancelled ? {
        cancelled: null
    } : value == EventStatus.completed ? {
        completed: null
    } : value == EventStatus.planned ? {
        planned: null
    } : value == EventStatus.confirmed ? {
        confirmed: null
    } : value == EventStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
